"""Alert Rule Engine — Evaluates rules against intelligence state.

Supports threshold, anomaly, correlation, and trend rule types.
"""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any, Dict, List, Optional, Union
from uuid import uuid4

import structlog
from pydantic import BaseModel, ConfigDict, Field

from ..agents.extractor import IntelligenceState

logger = structlog.get_logger(__name__)


class AlertRule(BaseModel):
    """Alert rule definition.

    Attributes:
        id: Unique rule identifier
        tenant_id: Tenant identifier
        name: Human-readable rule name
        rule_type: Type of rule (threshold, anomaly, correlation, trend)
        condition: Rule-specific condition dict
        severity: Alert severity (info, warning, critical)
        channels: Notification channels (slack, email, webhook)
        is_active: Whether rule is active
        created_at: Creation timestamp
        updated_at: Last update timestamp
    """

    model_config = ConfigDict(extra="forbid")

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    tenant_id: str = Field(..., description="Tenant identifier")
    name: str = Field(..., description="Human-readable rule name")
    rule_type: str = Field(
        ...,
        description="Rule type: threshold, anomaly, correlation, trend"
    )
    condition: Dict[str, Any] = Field(
        ...,
        description="Rule-specific condition",
    )
    severity: str = Field(
        default="warning",
        description="Alert severity: info, warning, critical",
    )
    channels: List[str] = Field(
        default_factory=list,
        description="Notification channels: slack, email, webhook",
    )
    is_active: bool = Field(default=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class Alert(BaseModel):
    """Alert generated by a triggered rule.

    Attributes:
        id: Unique alert identifier
        tenant_id: Tenant identifier
        rule_id: Rule identifier that triggered
        rule_name: Name of the rule that triggered
        severity: Alert severity
        message: Human-readable alert message
        evidence: Pointers to supporting data (URIs)
        created_at: Alert creation timestamp
    """

    model_config = ConfigDict(extra="forbid")

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    tenant_id: str = Field(..., description="Tenant identifier")
    rule_id: str = Field(..., description="Rule identifier")
    rule_name: str = Field(..., description="Rule name")
    severity: str = Field(..., description="Alert severity")
    message: str = Field(..., description="Human-readable alert message")
    evidence: Dict[str, Any] = Field(default_factory=dict, description="Pointers to supporting data")
    created_at: datetime = Field(default_factory=datetime.utcnow)


class AlertRuleEngine:
    """Evaluates alert rules against intelligence state.

    Supports four rule types:
    - threshold: Metric exceeds/falls below threshold
    - anomaly: Anomaly detected with severity
    - correlation: Correlation detected with minimum strength
    - trend: Trend detected with direction and z-score
    """

    def __init__(self) -> None:
        self._operators = {
            "gt": lambda a, b: a > b,
            "gte": lambda a, b: a >= b,
            "lt": lambda a, b: a < b,
            "lte": lambda a, b: a <= b,
            "eq": lambda a, b: a == b,
            "neq": lambda a, b: a != b,
        }

    async def evaluate(
        self,
        state: Any,
        rules: List[AlertRule],
    ) -> List[Any]:
        """Evaluate all active rules against intelligence state.

        Args:
            state: IntelligenceState with extracted entities, correlations, trends, anomalies
            rules: List of AlertRule to evaluate

        Returns:
            List of triggered Alert objects
        """
        triggered_alerts = []

        for rule in rules:
            if not rule.is_active:
                continue

            try:
                alerts = await self._evaluate_rule(state, rule)
                triggered_alerts.extend(alerts)
            except Exception as e:
                structlog.get_logger().error(
                    "rule_evaluation_failed",
                    rule_id=rule.id,
                    rule_name=rule.name,
                    error=str(e),
                )

        return triggered_alerts

    async def _evaluate_rule(
        self,
        state: Any,
        rule: AlertRule,
    ) -> List[Any]:
        """Evaluate a single rule against state."""
        if rule.rule_type == "threshold":
            return await self._evaluate_threshold(state, rule)
        elif rule.rule_type == "anomaly":
            return await self._evaluate_anomaly(state, rule)
        elif rule.rule_type == "correlation":
            return await self._evaluate_correlation(state, rule)
        elif rule.rule_type == "trend":
            return await self._evaluate_trend(state, rule)
        else:
            structlog.get_logger().warning(
                "unknown_rule_type",
                rule_type=rule.rule_type,
                rule_id=rule.id,
            )
            return []

    async def _evaluate_threshold(self, state: Any, rule: AlertRule) -> List[Any]:
        """Evaluate threshold rule against state.

        Condition format:
        {
            "metric": "pricing_delta|mention_frequency|hiring_velocity|sentiment",
            "operator": "gt|gte|lt|lte|eq|neq",
            "value": 0.15,
            "entity_filter": {"type": "Company", "name": "Apple"}  # optional
        }
        """
        condition = rule.condition
        metric = condition.get("metric")
        operator = condition.get("operator", "gt")
        threshold = condition.get("value", 0)
        entity_filter = condition.get("entity_filter")

        if not metric or operator not in self._operators:
            return []

        op_func = self._operators[operator]
        triggered = []

        # Extract metrics from state based on metric type
        # This would query the state for relevant metrics
        # For now, we'll check extracted entities and content_uris for relevant data
        metrics = self._extract_metrics(state, metric)

        for entity_name, value in metrics.items():
            if entity_filter and entity_filter.get("name") not in entity_name:
                continue

            if op_func(value, threshold):
                alert = self._create_alert(
                    rule=rule,
                    message=f"{metric} for {entity_name} ({value:.2f}) {operator} threshold ({threshold})",
                    evidence={
                        "metric": metric,
                        "value": value,
                        "threshold": threshold,
                        "operator": operator,
                        "entity": entity_name,
                    },
                )
                triggered.append(alert)

        return triggered

    async def _evaluate_anomaly(self, state: Any, rule: AlertRule) -> List[Any]:
        """Evaluate anomaly rule against state.

        Condition format:
        {
            "severity": "high|medium|low",
            "entity_types": ["Company", "Product"]  # optional
        }
        """
        condition = rule.condition
        target_severity = condition.get("severity", "high")
        entity_types = condition.get("entity_types", ["Company", "Product"])

        triggered = []

        # Check anomalies in state (from anomaly detector)
        anomalies = state.get("extracted_entities", [])  # Would come from anomaly detector
        # For now, check if state has anomaly indicators

        # This would check actual anomaly data from state
        # For now, return empty - actual implementation would query anomaly data
        return triggered

    async def _evaluate_correlation(self, state: Any, rule: AlertRule) -> List[Any]:
        """Evaluate correlation rule against state.

        Condition format:
        {
            "correlation_type": "pricing|talent|co_mention|patent",
            "min_strength": 0.7
        }
        """
        condition = rule.condition
        corr_type = condition.get("correlation_type")
        min_strength = condition.get("min_strength", 0.7)

        if not corr_type:
            return []

        triggered = []

        # Check correlations in state (from correlation engine)
        correlations = state.get("correlation_graph_delta", [])

        # This would check actual correlation data from state
        # For now, return empty - actual implementation would parse correlation data
        return triggered

    async def _evaluate_trend(self, state: Any, rule: AlertRule) -> List[Any]:
        """Evaluate trend rule against state.

        Condition format:
        {
            "trend_type": "pricing|hiring|mention_frequency|sentiment",
            "direction": "up|down|anomalous",
            "z_score_min": 2.0
        }
        """
        condition = rule.condition
        trend_type = condition.get("trend_type")
        direction = condition.get("direction")
        z_score_min = condition.get("z_score_min", 2.0)

        if not trend_type or not direction:
            return []

        triggered = []

        # Check trends in state (from trend analyzer)
        trends = state.get("briefing_section_uris", [])  # Would come from trend analyzer

        # This would check actual trend data from state
        return triggered

    def _extract_metrics(self, state: Any, metric: str) -> Dict[str, float]:
        """Extract metric values from state.

        Args:
            state: IntelligenceState
            metric: Metric name to extract

        Returns:
            Dict mapping entity_name to metric value
        """
        # This would extract actual metrics from state
        # For now, return empty dict
        return {}

    def _create_alert(
        self,
        rule: AlertRule,
        message: str,
        evidence: Dict[str, Any],
    ) -> Any:
        """Create an Alert object from a triggered rule."""
        from ..alerts.rules import Alert
        return Alert(
            tenant_id=rule.tenant_id,
            rule_id=rule.id,
            rule_name=rule.name,
            severity=rule.severity,
            message=message,
            evidence=evidence,
        )